#!/bin/bash
VERT="\\033[0;32m"
NORMAL="\\033[0;39m"
ROUGE="\\033[1;31m"
ROSE="\\033[1;35m"
BLEU="\\033[1;34m"
BLANC="\\033[0;02m"
BLANCLAIR="\\033[1;08m"
JAUNE="\\033[1;33m"
CYAN="\\033[1;36m"

LICFILE="misc/lic.txt"
NL=$(cat $LICFILE |wc -l)

function checklicence {
	if [[ $(head -n$NL "$1") = $(head -n$NL "misc/lic.txt") ]]
	then 
		echo -e "$VERT" "ok   : $1"
		return 0
	else
		echo -e "$ROUGE" "fail : $1"
		return 1
	fi
}

rvalue=0
cc=$(find src/ -name '*.cc' -type f )
hh=$(find src/ -name '*.hh' -type f )

for i in $cc $hh ; do
	if !(checklicence $i)
	then
		rvalue=$(expr $rvalue + 1)
	fi
done

if [[ $rvalue != 0 ]]
then 
	echo -e $ROUGE "********************************************"
	echo -e $ROUGE "* Some files seems to have a wrong licence *"
	echo -e $ROUGE "********************************************"
	echo -e $BLEU  "** $rvalue file(s) need to be manually checked **"
else
	echo -e $VERT "********************************************"
	echo -e $VERT "*         Everything seems allwright       *"
	echo -e $VERT "********************************************"
fi
exit $rvalue
