#!/bin/bash
VERT="\\033[0;32m"
JAUNE="\\033[1;33m"
NORMAL="\\033[0;39m"
ROUGE="\\033[1;31m"
ROSE="\\033[1;35m"
BLEU="\\033[1;34m"
BLANC="\\033[0;02m"
BLANCLAIR="\\033[1;08m"
JAUNE="\\033[1;33m"
CYAN="\\033[1;36m"

LICFILE="misc/lic.txt"
BINCOPYRIGHT=debian/copy.bin
NL=$(cat $LICFILE |wc -l)
function includefile {
 return  $(diff $1 $2 |grep '^>' | wc -l)
}
function checklicence {
	if $(includefile $1 misc/headcopyright.txt)
	then
		echo -en $VERT  'copyright...ok'
	else
		echo -en $ROUGE 'bad copyright?'
	fi

		echo -en '\t|\t'

	if $(includefile $1  misc/lic.txt)
	then
		echo -e "$VERT" "ok \t: $1"
		return 0
	fi


	if $(includefile $1 misc/nokia.txt)
	then
		echo -en "$BLEU" "nokia"
		echo -e "$VERT" "\t: $1"
		return 0
	fi

	if $(includefile $1 misc/bsd.txt)
	then
		echo -en "$ROSE" "bsd"
		echo -e "$VERT" "\t: $1"
		return 0
	fi

	echo -e "$ROUGE" "fail\t: $1"
	return 1
}

badtextfiles=0
self=$0
cc=$(find src/ -name '*.cc' -type f )
hh=$(find src/ -name '*.hh' -type f )

for i in $self $cc $hh ; do
	if !(checklicence $i)
	then
		badtextfiles=$(expr $badtextfiles + 1)
	fi
done

if [[ $badtextfiles != 0 ]]
then
	echo -e $ROUGE "********************************************"
	echo -e $ROUGE "* Some files seems to have a wrong licence *"
	echo -e $ROUGE "********************************************"
	echo -e $BLEU  "** $badtextfiles file(s) need to be manually checked **"
else
	echo -e $VERT "********************************************"
	echo -e $VERT "*         Everything seems allwright       *"
	echo -e $VERT "********************************************"
fi
echo -en $NORMAL

###### fin du check pour les fichiers de code ######
badbinaryfiles=0

# some check that the liscence file is correct:
# first no white space
j=$(egrep ' ' $BINCOPYRIGHT |grep -v '#'|wc -l)
if [[ $j != 0 ]]
then 
	echo -e $ROUGE "le fichier de définition de licence contient des espace, assrez vous qu'il ne contien que des tabulations !"
	egrep ' ' $BINCOPYRIGHT|grep -v '#'
	exit -1;
fi

#second non double tbulation 
j=$(egrep '\s\s' $BINCOPYRIGHT |grep -v '#'|wc -l)
if [[ $j != 0 ]]
then 
	echo -e $ROUGE "le fichier de définition de licence contient des doubles tabulations ! merci de les retirés! vérifiez les lignes suiventes :" $NORMAL
	egrep '\s\s' $BINCOPYRIGHT |grep -v '#'
	exit -1;
fi

# let's check if the file is in the liscence file 
icns=$(find icons -name '*' -type f)

for i in $icns ; do 
	j=$(grep $i $BINCOPYRIGHT|wc -l)
	str=$(grep $i $BINCOPYRIGHT|cut -f1)
	if [[ $j == 0 || $str == 'Licence' || $str == 'Nothing' ]]
	then 
		echo -e $ROUGE "Nothing : $i"
		badbinaryfiles=$(expr $badbinaryfiles + 1 );
	else
		echo -e $VERT $(grep $i $BINCOPYRIGHT)
	fi
done

nexfile=0
# let's check that every file in the liscence file exist
tf=$(cat $BINCOPYRIGHT|grep -v '#'|cut -f3)
for i in $tf ; do 
	if [ ! -e $i ]
	then
		echo -e $ROUGE "fichier non existant : $i"
		nexfile=$(expr $nexfile + 1);
	fi
	if [ -d $i ]
	then 
		echo -e $BLEU "dou you really think you can copyright a directory ?" $i 
	fi
	
done

echo -e $BLEU "you have"
echo -e $BLEU "$badtextfiles source file(s) witt an issue on the copiright and/or liscence"
echo -e $BLEU "$badbinaryfiles binaru file(s) with no liscence or not appearing in the copyright file"
echo -e $BLEU "$nexfile non existant files repertoried in the copyright file"
sum=$(expr $badtextfiles + $badbinaryfiles + $nexfile)
exit $sum
