Document: songbook-client
Title: Debian songbook-client Manual
Author: <insert document author here>
Abstract: This manual describes what songbook-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/songbook-client/songbook-client.sgml.gz

Format: postscript
Files: /usr/share/doc/songbook-client/songbook-client.ps.gz

Format: text
Files: /usr/share/doc/songbook-client/songbook-client.text.gz

Format: HTML
Index: /usr/share/doc/songbook-client/html/index.html
Files: /usr/share/doc/songbook-client/html/*.html
